-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."notes_labels" add column "rating" integer
--  not null default '0';
