-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."heroes" add column "activated" boolean
--  not null default 'false';
